/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContentContainer {
    }
    interface HeaderText {
    }
    interface LoginFooter {
    }
    interface LoginForm {
        /**
          * Prop: forgotPasswordUrl: string Page to redirect to if user se;ects forgot password
         */
        "forgotPasswordUrl": string;
    }
    interface LoginHeader {
        /**
          * The brand
         */
        "brand": string;
    }
    interface LoginTitleWrapper {
    }
    interface MainHeader {
        "brand": string;
    }
    interface PageLogo {
        "brand": string;
    }
    interface ProductTile {
        /**
          * The link for the product
         */
        "linkText": string;
        /**
          * The image to display
         */
        "productImage": string;
    }
    interface TextTitleBar {
    }
    interface TileContainer {
    }
}
export interface LoginFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLoginFormElement;
}
declare global {
    interface HTMLContentContainerElement extends Components.ContentContainer, HTMLStencilElement {
    }
    var HTMLContentContainerElement: {
        prototype: HTMLContentContainerElement;
        new (): HTMLContentContainerElement;
    };
    interface HTMLHeaderTextElement extends Components.HeaderText, HTMLStencilElement {
    }
    var HTMLHeaderTextElement: {
        prototype: HTMLHeaderTextElement;
        new (): HTMLHeaderTextElement;
    };
    interface HTMLLoginFooterElement extends Components.LoginFooter, HTMLStencilElement {
    }
    var HTMLLoginFooterElement: {
        prototype: HTMLLoginFooterElement;
        new (): HTMLLoginFooterElement;
    };
    interface HTMLLoginFormElement extends Components.LoginForm, HTMLStencilElement {
    }
    var HTMLLoginFormElement: {
        prototype: HTMLLoginFormElement;
        new (): HTMLLoginFormElement;
    };
    interface HTMLLoginHeaderElement extends Components.LoginHeader, HTMLStencilElement {
    }
    var HTMLLoginHeaderElement: {
        prototype: HTMLLoginHeaderElement;
        new (): HTMLLoginHeaderElement;
    };
    interface HTMLLoginTitleWrapperElement extends Components.LoginTitleWrapper, HTMLStencilElement {
    }
    var HTMLLoginTitleWrapperElement: {
        prototype: HTMLLoginTitleWrapperElement;
        new (): HTMLLoginTitleWrapperElement;
    };
    interface HTMLMainHeaderElement extends Components.MainHeader, HTMLStencilElement {
    }
    var HTMLMainHeaderElement: {
        prototype: HTMLMainHeaderElement;
        new (): HTMLMainHeaderElement;
    };
    interface HTMLPageLogoElement extends Components.PageLogo, HTMLStencilElement {
    }
    var HTMLPageLogoElement: {
        prototype: HTMLPageLogoElement;
        new (): HTMLPageLogoElement;
    };
    interface HTMLProductTileElement extends Components.ProductTile, HTMLStencilElement {
    }
    var HTMLProductTileElement: {
        prototype: HTMLProductTileElement;
        new (): HTMLProductTileElement;
    };
    interface HTMLTextTitleBarElement extends Components.TextTitleBar, HTMLStencilElement {
    }
    var HTMLTextTitleBarElement: {
        prototype: HTMLTextTitleBarElement;
        new (): HTMLTextTitleBarElement;
    };
    interface HTMLTileContainerElement extends Components.TileContainer, HTMLStencilElement {
    }
    var HTMLTileContainerElement: {
        prototype: HTMLTileContainerElement;
        new (): HTMLTileContainerElement;
    };
    interface HTMLElementTagNameMap {
        "content-container": HTMLContentContainerElement;
        "header-text": HTMLHeaderTextElement;
        "login-footer": HTMLLoginFooterElement;
        "login-form": HTMLLoginFormElement;
        "login-header": HTMLLoginHeaderElement;
        "login-title-wrapper": HTMLLoginTitleWrapperElement;
        "main-header": HTMLMainHeaderElement;
        "page-logo": HTMLPageLogoElement;
        "product-tile": HTMLProductTileElement;
        "text-title-bar": HTMLTextTitleBarElement;
        "tile-container": HTMLTileContainerElement;
    }
}
declare namespace LocalJSX {
    interface ContentContainer {
    }
    interface HeaderText {
    }
    interface LoginFooter {
    }
    interface LoginForm {
        /**
          * Prop: forgotPasswordUrl: string Page to redirect to if user se;ects forgot password
         */
        "forgotPasswordUrl"?: string;
        /**
          * Event: loginShouldOccur: EventEmitter Event to fire if data validates
         */
        "onLoginShouldOccur"?: (event: LoginFormCustomEvent<any>) => void;
    }
    interface LoginHeader {
        /**
          * The brand
         */
        "brand"?: string;
    }
    interface LoginTitleWrapper {
    }
    interface MainHeader {
        "brand"?: string;
    }
    interface PageLogo {
        "brand"?: string;
    }
    interface ProductTile {
        /**
          * The link for the product
         */
        "linkText"?: string;
        /**
          * The image to display
         */
        "productImage"?: string;
    }
    interface TextTitleBar {
    }
    interface TileContainer {
    }
    interface IntrinsicElements {
        "content-container": ContentContainer;
        "header-text": HeaderText;
        "login-footer": LoginFooter;
        "login-form": LoginForm;
        "login-header": LoginHeader;
        "login-title-wrapper": LoginTitleWrapper;
        "main-header": MainHeader;
        "page-logo": PageLogo;
        "product-tile": ProductTile;
        "text-title-bar": TextTitleBar;
        "tile-container": TileContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "content-container": LocalJSX.ContentContainer & JSXBase.HTMLAttributes<HTMLContentContainerElement>;
            "header-text": LocalJSX.HeaderText & JSXBase.HTMLAttributes<HTMLHeaderTextElement>;
            "login-footer": LocalJSX.LoginFooter & JSXBase.HTMLAttributes<HTMLLoginFooterElement>;
            "login-form": LocalJSX.LoginForm & JSXBase.HTMLAttributes<HTMLLoginFormElement>;
            "login-header": LocalJSX.LoginHeader & JSXBase.HTMLAttributes<HTMLLoginHeaderElement>;
            "login-title-wrapper": LocalJSX.LoginTitleWrapper & JSXBase.HTMLAttributes<HTMLLoginTitleWrapperElement>;
            "main-header": LocalJSX.MainHeader & JSXBase.HTMLAttributes<HTMLMainHeaderElement>;
            "page-logo": LocalJSX.PageLogo & JSXBase.HTMLAttributes<HTMLPageLogoElement>;
            "product-tile": LocalJSX.ProductTile & JSXBase.HTMLAttributes<HTMLProductTileElement>;
            "text-title-bar": LocalJSX.TextTitleBar & JSXBase.HTMLAttributes<HTMLTextTitleBarElement>;
            "tile-container": LocalJSX.TileContainer & JSXBase.HTMLAttributes<HTMLTileContainerElement>;
        }
    }
}
