/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LoginTitleWrapper {
    }
    interface PageHeader {
        /**
          * The brand
         */
        "brand": string;
    }
}
declare global {
    interface HTMLLoginTitleWrapperElement extends Components.LoginTitleWrapper, HTMLStencilElement {
    }
    var HTMLLoginTitleWrapperElement: {
        prototype: HTMLLoginTitleWrapperElement;
        new (): HTMLLoginTitleWrapperElement;
    };
    interface HTMLPageHeaderElement extends Components.PageHeader, HTMLStencilElement {
    }
    var HTMLPageHeaderElement: {
        prototype: HTMLPageHeaderElement;
        new (): HTMLPageHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "login-title-wrapper": HTMLLoginTitleWrapperElement;
        "page-header": HTMLPageHeaderElement;
    }
}
declare namespace LocalJSX {
    interface LoginTitleWrapper {
    }
    interface PageHeader {
        /**
          * The brand
         */
        "brand"?: string;
    }
    interface IntrinsicElements {
        "login-title-wrapper": LoginTitleWrapper;
        "page-header": PageHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "login-title-wrapper": LocalJSX.LoginTitleWrapper & JSXBase.HTMLAttributes<HTMLLoginTitleWrapperElement>;
            "page-header": LocalJSX.PageHeader & JSXBase.HTMLAttributes<HTMLPageHeaderElement>;
        }
    }
}
