/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContentContainer {
    }
    interface HeaderText {
    }
    interface LoginTitleWrapper {
    }
    interface PageHeader {
        /**
          * The brand
         */
        "brand": string;
    }
    interface ProductTile {
        /**
          * The link for the product
         */
        "linkText": string;
        /**
          * The image to display
         */
        "productImage": string;
    }
    interface TextTitleBar {
    }
    interface TileContainer {
    }
}
declare global {
    interface HTMLContentContainerElement extends Components.ContentContainer, HTMLStencilElement {
    }
    var HTMLContentContainerElement: {
        prototype: HTMLContentContainerElement;
        new (): HTMLContentContainerElement;
    };
    interface HTMLHeaderTextElement extends Components.HeaderText, HTMLStencilElement {
    }
    var HTMLHeaderTextElement: {
        prototype: HTMLHeaderTextElement;
        new (): HTMLHeaderTextElement;
    };
    interface HTMLLoginTitleWrapperElement extends Components.LoginTitleWrapper, HTMLStencilElement {
    }
    var HTMLLoginTitleWrapperElement: {
        prototype: HTMLLoginTitleWrapperElement;
        new (): HTMLLoginTitleWrapperElement;
    };
    interface HTMLPageHeaderElement extends Components.PageHeader, HTMLStencilElement {
    }
    var HTMLPageHeaderElement: {
        prototype: HTMLPageHeaderElement;
        new (): HTMLPageHeaderElement;
    };
    interface HTMLProductTileElement extends Components.ProductTile, HTMLStencilElement {
    }
    var HTMLProductTileElement: {
        prototype: HTMLProductTileElement;
        new (): HTMLProductTileElement;
    };
    interface HTMLTextTitleBarElement extends Components.TextTitleBar, HTMLStencilElement {
    }
    var HTMLTextTitleBarElement: {
        prototype: HTMLTextTitleBarElement;
        new (): HTMLTextTitleBarElement;
    };
    interface HTMLTileContainerElement extends Components.TileContainer, HTMLStencilElement {
    }
    var HTMLTileContainerElement: {
        prototype: HTMLTileContainerElement;
        new (): HTMLTileContainerElement;
    };
    interface HTMLElementTagNameMap {
        "content-container": HTMLContentContainerElement;
        "header-text": HTMLHeaderTextElement;
        "login-title-wrapper": HTMLLoginTitleWrapperElement;
        "page-header": HTMLPageHeaderElement;
        "product-tile": HTMLProductTileElement;
        "text-title-bar": HTMLTextTitleBarElement;
        "tile-container": HTMLTileContainerElement;
    }
}
declare namespace LocalJSX {
    interface ContentContainer {
    }
    interface HeaderText {
    }
    interface LoginTitleWrapper {
    }
    interface PageHeader {
        /**
          * The brand
         */
        "brand"?: string;
    }
    interface ProductTile {
        /**
          * The link for the product
         */
        "linkText"?: string;
        /**
          * The image to display
         */
        "productImage"?: string;
    }
    interface TextTitleBar {
    }
    interface TileContainer {
    }
    interface IntrinsicElements {
        "content-container": ContentContainer;
        "header-text": HeaderText;
        "login-title-wrapper": LoginTitleWrapper;
        "page-header": PageHeader;
        "product-tile": ProductTile;
        "text-title-bar": TextTitleBar;
        "tile-container": TileContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "content-container": LocalJSX.ContentContainer & JSXBase.HTMLAttributes<HTMLContentContainerElement>;
            "header-text": LocalJSX.HeaderText & JSXBase.HTMLAttributes<HTMLHeaderTextElement>;
            "login-title-wrapper": LocalJSX.LoginTitleWrapper & JSXBase.HTMLAttributes<HTMLLoginTitleWrapperElement>;
            "page-header": LocalJSX.PageHeader & JSXBase.HTMLAttributes<HTMLPageHeaderElement>;
            "product-tile": LocalJSX.ProductTile & JSXBase.HTMLAttributes<HTMLProductTileElement>;
            "text-title-bar": LocalJSX.TextTitleBar & JSXBase.HTMLAttributes<HTMLTextTitleBarElement>;
            "tile-container": LocalJSX.TileContainer & JSXBase.HTMLAttributes<HTMLTileContainerElement>;
        }
    }
}
